### ISSUE TITLE
Create english version of documentation

### ISSUE THREAD

**Issue by AlexKirkouski** [lsfusion/samples#3]

**Comment by AlexKirkouski** [comment]
Code that was used to clean and export from confluence
`--action runFromPageList  --space "zclipagesh1"  --title "AAA"  --descendents  --continue  --common "-a copyPage --id @pageId@ --newSpace zclipagesh2 --parent @source --replace"		
		
./confluence.sh --action runFromPageList --space "LSFUS"  --common "--action removeContentVersions --id @pageId@"		
./confluence.sh --action runFromAttachmentList --space "LSFUS"  --common '--action removeAttachment --id @pageId@ --name "@attachment@"'		
./confluence.sh --action runFromPageList --space "LSFUS" --title "Temp" --descendents --common "--action removePage --id @pageId@"		
./confluence.sh --action removeTrash --space "LSFUS"		
		
SELECT c.title,b.* INTO bnodr2 FROM bodycontent b JOIN content c ON b.contentid=c.contentid WHERE c.prevver IS NULL AND c.contenttype='PAGE' AND c.content_status='current'		
SELECT c.title,b.* INTO bnodr2 FROM bodycontent b JOIN (SELECT contentid, MAX(title) AS title FROM content GROUP BY contentid) JOIN content c ON b.contentid=c.contentid		
		
COPY (SELECT table_to_xml('bnodr', true, false, '')) to '/home/pg/file2.xml';		
		
CREATE OR REPLACE FUNCTION copytotest() RETURNS void AS $$		
DECLARE		
    r int8;		
BEGIN		
FOR r IN SELECT bodycontentid FROM bnodr2 WHERE body IS NOT NULL AND title IS NOT NULL		
	LOOP	
		EXECUTE 'COPY (SELECT trim(body) FROM bnodr2 WHERE bodycontentid = '||r||') TO ''/home/pg/test/' || (SELECT replace(trim(title),'/','_') FROM bnodr2 WHERE bodycontentid = r) || '_' || r || '.html''';
	END LOOP;	
END;		
$$ LANGUAGE PLPGSQL;		
		
SELECT copytotest()		
`

**Comment by AlexKirkouski** [comment]
Simple function can be used:
```
CREATE OR REPLACE FUNCTION readFile(file text)  
  RETURNS text AS $$
    DECLARE
      content text;
      tmp text;
    BEGIN
      file := quote_literal(file);
      tmp := 'tmpReadFile';

      EXECUTE 'CREATE TEMP TABLE ' || tmp || ' (content text)';
      EXECUTE 'COPY ' || tmp || ' FROM ' || file;
      EXECUTE 'SELECT content FROM ' || tmp INTO content;
      EXECUTE 'DROP TABLE ' || tmp;

      RETURN content;
	EXCEPTION
		WHEN OTHERS THEN
        	RETURN NULL;
    END;
  $$ LANGUAGE plpgsql VOLATILE;
```

**Comment by AlexKirkouski** [comment]
CLEANING DRAFTS AND PREVIOUS VERSIONS
First install CLI connector 
https://marketplace.atlassian.com/apps/284/confluence-command-line-interface-cli?hosting=server&tab=overview
Then CLI Client (just download somewhere, and yum install java because it needs it)
https://bobswift.atlassian.net/wiki/spaces/ACLI/pages/98009238/CLI+Client+Installation+and+Use
Then acli-server.properties -> acli.properties setting credentials and myconfluence to http://localhost:8090
Then in that dir execute:
``./acli.sh --action   runFromPageList --space "LSFUS"    --common "--action removeContentVersions --id @pageId@"
``
``
./acli.sh --action   removeTrash --space "LSFUS"
``
PS: To remove attachments and temp pages :
./acli.sh --action   runFromAttachmentList --space "LSFUS"  --common '--action removeAttachment --id   @pageId@ --name "@attachment@"'
./acli.sh --action runFromPageList   --space "LSFUS" --title "Temp" --descendents --common   "--action removePage --id @pageId@"

**Comment by AlexKirkouski** [comment]
Code for restoring from var/lib/pgsql/data/pg_imp dir (owner should be postgres):
```
CREATE OR REPLACE FUNCTION readFile(file text) RETURNS TEXT AS 
$$
BEGIN
	RETURN pg_read_file(file);
EXCEPTION
  WHEN OTHERS THEN
    RETURN NULL;
END;
$$ LANGUAGE 'plpgsql' VOLATILE;

SELECT bodycontentid, readFile('pg_imp/' || bodycontent.bodycontentid || '.html') AS file INTO bodyread FROM bodycontent;
UPDATE bodycontent SET body = bodyread.file FROM bodyread WHERE bodycontent.bodycontentid=bodyread.bodycontentid AND bodyread.file IS NOT NULL
```

**Comment by AlexKirkouski** [comment]
To rename files to get only ids : Total commander -> Find .*_ and set regex check.

**Comment by AlexKirkouski** [comment]
Also after import Administration -> Context indexing should be run

**Comment by pavel-miniutka** [comment]
remove all drafts
```
select * into temp_conf from CONTENT where (CONTENTTYPE = 'PAGE') AND (CONTENT_STATUS = 'draft');
DELETE FROM CONTENT_LABEL WHERE CONTENTID IN (SELECT CONTENTID FROM temp_conf);
DELETE FROM CONFANCESTORS WHERE DESCENDENTID IN (SELECT CONTENTID FROM temp_conf);
DELETE FROM USERCONTENT_RELATION WHERE TARGETCONTENTID in (SELECT CONTENTID FROM temp_conf);
DELETE FROM LINKS WHERE CONTENTID in (SELECT CONTENTID FROM temp_conf);
DELETE FROM CONTENTPROPERTIES WHERE CONTENTID in (SELECT CONTENTID FROM temp_conf);
DELETE FROM BODYCONTENT WHERE CONTENTID IN (SELECT CONTENTID FROM temp_conf);
DELETE FROM CONTENT WHERE CONTENTID in (SELECT CONTENTID FROM temp_conf);
DROP TABLE temp_conf;
```
